name: Build, Check, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  PY_COLORS: "1"

permissions:
  contents: read

jobs:
  build_and_test:
    name: Build, Check, Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Install Rust 1.85.0
      uses: dtolnay/rust-toolchain@0acae73baee12cc81c9b1fb9e8f8b7672bf17c6a # 1.85.0
      with:
        toolchain: 1.85.0
        targets: ""
        components: rustfmt, clippy
    - name: Set Up Python 3.11
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: 3.11
    - name: Install
      run: |
        pip install --upgrade pip
        pip install ./py/pica/
        pip install pytest=="7.4.4"
        pip install pytest_asyncio=="0.23.3"
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Fmt
      run: cargo fmt --check --quiet
    - name: Clippy
      run: cargo clippy --no-deps -- --deny warnings
    - name: Run Python tests suite
      run: pytest --log-cli-level=DEBUG -v
