name: Build, Check, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  PY_COLORS: "1"

jobs:
  build_and_test:
    name: Build, Check, Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust 1.67.1
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.67.1
        override: true
        components: rustfmt, clippy
    - name: Set Up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install
      run: |
        pip install --upgrade pip
        pip install ./py/pica/
        pip install pytest=="7.4.4"
        pip install pytest_asyncio=="0.23.3"
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Fmt
      run: cargo fmt --check --quiet
    - name: Clippy
      run: cargo clippy --no-deps -- --deny warnings
    - name: Run Python tests suite
      run: pytest --log-cli-level=DEBUG -v
